development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mical
  pool: 5

test: &test
  adapter: sqlite3
  database: <%= ENV['RAMTEST'] == 'true' ? '/Volumes/RAM Disk/test.sqlite3' : 'db/test.sqlite3' %>
  pool: 5
  timeout: 5000
  encoding: unicode

cucumber:
  <<: *test
