development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mical
  pool: 5
  username: dummy
  password: dummy
  
test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  encoding: unicode

cucumber:
  <<: *test