development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ical
  pool: 5
  username: pruebas
  password: pruebas
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  encoding: unicode
